# NumPy practice notebook

In [1]:
import numpy as np

In [4]:
np.linspace(1,2,5) # equally spaced elements

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.seed(3)
np.random.rand(3,4) # uniform distribution -> (0, 1)
np.random.randn(3,4) # Standard normal -> -ve floats included (-1,1)
np.random.randint(-100, 100, (2,3))

array([[-67,  23, -21],
       [ 76, -63, -80]])

In [22]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.shape

(25,)

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr = np.random.randint(10, 25, 10)
ranarr

array([10, 18, 24, 23, 17, 11, 12, 15, 12, 20])

In [39]:
ranarr.max()
ranarr.argmax()

2

In [43]:
a, b = 1, 2
a, b = b, a

In [44]:
a, b

(2, 1)

In [51]:
arr_2d = np.arange(5, 50, 5).reshape(3,3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d[0][2]
arr_2d[0,2]

15

In [59]:
arr[arr<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

7.211102550927978

In [69]:
arr_2d.sum()
arr_2d.sum(axis=0) # across rows
arr_2d.sum(axis=1) # across columns

array([ 30,  75, 120])